app.datasource.auth.url=jdbc:mysql://localhost:3306/auth_db
app.datasource.auth.username=${DB_USER:root}
app.datasource.auth.password=${DB_PASS:prabhi12}

app.datasource.erp.url=jdbc:mysql://localhost:3306/erp_db
app.datasource.erp.username=${DB_USER:root}
app.datasource.erp.password=${DB_PASS:prabhi12}

app.jwt.secret=${JWT_SECRET:changeme-in-prod-min-32-chars-long!!}
app.jwt.expiry-ms=86400000

spring.flyway.enabled=false

server.address=127.0.0.1
